services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27019:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - database
  api:
    build:
      context: "https://github.com/andrefs/shooting-stars-api.git#d960a4155f75e9d6a86f464a0c5ba2f515382f4a"
      dockerfile: Dockerfile
    pull_policy: build
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - front
      - back
      - database
    environment:
      MONGODB_HOST: mongo
      NODE_ENV: "production"
      API_PORT: 15111
    volumes:
      - api_export:/data/export
      - api_items:/data/items
      - api_images:/usr/src/ss-api/images
    ports:
      - "15111:15111"
  game:
    build:
      context: "https://github.com/andrefs/shooting-stars-game.git#5c33a02"
      dockerfile: Dockerfile
    pull_policy: build
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - front
    ports:
      - "3001:80"
  stats:
    build:
      context: "https://github.com/andrefs/shooting-stars-stats.git#7f30208c0a8828a4a302ca81984b588eda87b2c5"
      dockerfile: Dockerfile
    pull_policy: build
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - back
      - front
    ports:
      - "3002:3002"
volumes:
  mongo_data:
  api_export:
  api_items:
  api_images:
networks:
  database:
  front:
  back:
