services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
    ports:
      - "27019:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - database
  api:
    build:
      context: "https://github.com/andrefs/shooting-stars-api.git#9c82a10b61fd86e90bf9bc9932d96892bf2c7f39"
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - front
      - back
      - database
    environment:
      MONGODB_HOST: mongo
      NODE_ENV: "production"
      API_PORT: 15111
    volumes:
      - type: bind
        source: ./data/export
        target: /data/export
      - type: bind
        source: ./data/items
        target: /data/items
      - type: bind
        source: ./data/items/images
        target: /usr/src/ss-api/images
    ports:
      - "15111:15111"
  game:
    build:
      context: "https://github.com/andrefs/shooting-stars-game.git#d1e4fbfe14b84b50932166ef803da93ee64303b"
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - front
    ports:
      - "3001:80"
  stats:
    build:
      context: "https://github.com/andrefs/shooting-stars-stats.git#134b395459046ba36ea1385a71e34025142125aa"
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - back
      - front
    ports:
      - "3002:3002"
networks:
  database:
  front:
  back:
